version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    # ports:
      # - 27018:27017
    volumes:
      - mongo_db:/data/db

  # Node API service      
  api:
    #container_name: vircadia-metaverse-v2
    build: .
    # ports:
      # - 3030:3030
    volumes:
      - .:/usr/src/api
    environment:
     PORT: 3030
     MONGODB_URL: mongodb://mongodb_container:27017
     NAME: Vircadia
    depends_on:
      - mongo_db   
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d 
      - /etc/letsencrypt:/etc/letsencrypt
      - /opt/goobieverse-website/dist/spa:/opt/goobieverse-website/dist/spa 
    depends_on:
      - api 
    ports:
      - 3030:3030
      - 443:443
      - 80:80    
volumes:
  mongo_db: {}
