version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: vircadia_mongodb_container_v1
    image: mongo:latest
    restart: always
    #ports:
     # - 27018:27017
    volumes:
      - mongo_db:/data/db
  redis:
        container_name: vircadia_redis_container_v1
        restart: always
        image: redis/redis-stack:latest
        # command: redis-server --save 20 1 --loglevel warning
        volumes:
            - redis_server:/data/redis
  # Node API service      
  api:
    #container_name: vircadia-metaverse
    build: .
    # ports:
      # - 3030:3030
    volumes:
      - .:/usr/src/api
    environment:
     PORT: 3040
     MONGODB_URL: mongodb://vircadia_mongodb_container_v1:27017
     REDIS_URL: redis://vircadia_redis_container_v1:6379
     NAME: Vircadia
    depends_on:
      - mongo_db  
      - redis 
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d 
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
    ports:
      - 3040:3040
      - 445:445 
volumes:
  mongo_db: {}
  redis_server: {}
